service: springboot-kotlin-lambda

provider:
  name: aws
  runtime: java8
  memorySize: 256
  timeout: 60
  region: eu-west-1

package:
  artifact: build/distributions/springboot-kotlin-lambda-1.0.0.zip

functions:
  leftComparer:
    handler: net.aykutaras.lambda.LeftStoreLambdaHandler
    events:
      - http:
          path: api/v1/{id}/left
          method: post

  rightComparer:
    handler: net.aykutaras.lambda.RightStoreLambdaHandler
    events:
      - http:
          path: api/v1/{id}/right
          method: post

  diffResults:
    handler: net.aykutaras.lambda.DiffLambdaHandler
    events:
      - http:
          path: api/v1/{id}
          method: get
