service: aaras-springboot

provider:
  name: aws
  runtime: java8
  memorySize: 256
  timeout: 60
  region: eu-west-1

package:
  artifact: build/distributions/springboot-kotlin-lambda.zip

functions:
  leftComparer:
    handler: com.serverless.LambdaHandler
    events:
      - http:
          path: api/v1/{id}/left
          method: post

